/*
 * SHOPPERS COMMUNITY API
 * Endpoints for the Shoppers community backend
 *
 * OpenAPI spec version: 1.0.0
 * Contact: joelnyongesa148@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IdReviewsBody model module.
 * @module model/IdReviewsBody
 * @version 1.0.0
 */
export class IdReviewsBody {
  /**
   * Constructs a new <code>IdReviewsBody</code>.
   * @alias module:model/IdReviewsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IdReviewsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdReviewsBody} obj Optional instance to populate.
   * @return {module:model/IdReviewsBody} The populated <code>IdReviewsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdReviewsBody();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('star_rating'))
        obj.starRating = ApiClient.convertToType(data['star_rating'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
IdReviewsBody.prototype.description = undefined;

/**
 * @member {Number} starRating
 */
IdReviewsBody.prototype.starRating = undefined;

