/*
 * SHOPPERS COMMUNITY API
 * Endpoints for the Shoppers community backend
 *
 * OpenAPI spec version: 1.0.0
 * Contact: joelnyongesa148@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShoppersCommunityApi);
  }
}(this, function(expect, ShoppersCommunityApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IdReviewsBody', function() {
      beforeEach(function() {
        instance = new ShoppersCommunityApi.IdReviewsBody();
      });

      it('should create an instance of IdReviewsBody', function() {
        // TODO: update the code to test IdReviewsBody
        expect(instance).to.be.a(ShoppersCommunityApi.IdReviewsBody);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property starRating (base name: "star_rating")', function() {
        // TODO: update the code to test the property starRating
        expect(instance).to.have.property('starRating');
        // expect(instance.starRating).to.be(expectedValueLiteral);
      });

    });
  });

}));
