/*
 * SHOPPERS COMMUNITY API
 * Endpoints for the Shoppers community backend
 *
 * OpenAPI spec version: 1.0.0
 * Contact: joelnyongesa148@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {IdReviewsBody} from './model/IdReviewsBody';
import {LoginBody} from './model/LoginBody';
import {SignupBody} from './model/SignupBody';
import {SEARCHQUERIESApi} from './api/SEARCHQUERIESApi';
import {USERSApi} from './api/USERSApi';
import {USERSAUTHENTICATIONApi} from './api/USERSAUTHENTICATIONApi';

/**
* Endpoints_for_the_Shoppers_community_backend.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ShoppersCommunityApi = require('index'); // See note below*.
* var xxxSvc = new ShoppersCommunityApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ShoppersCommunityApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ShoppersCommunityApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ShoppersCommunityApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The IdReviewsBody model constructor.
     * @property {module:model/IdReviewsBody}
     */
    IdReviewsBody,

    /**
     * The LoginBody model constructor.
     * @property {module:model/LoginBody}
     */
    LoginBody,

    /**
     * The SignupBody model constructor.
     * @property {module:model/SignupBody}
     */
    SignupBody,

    /**
    * The SEARCHQUERIESApi service constructor.
    * @property {module:api/SEARCHQUERIESApi}
    */
    SEARCHQUERIESApi,

    /**
    * The USERSApi service constructor.
    * @property {module:api/USERSApi}
    */
    USERSApi,

    /**
    * The USERSAUTHENTICATIONApi service constructor.
    * @property {module:api/USERSAUTHENTICATIONApi}
    */
    USERSAUTHENTICATIONApi
};
